import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BELAL.H",
  description: "Generated by create belel hossain",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers >
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </Providers>
  );
}
